name: Go
on: [push]
jobs:

  build:
    name: Build
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
